server:
  port: 10010

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user_info
          uri: http://localhost:8081 # http://localhost:8082 # lb://user_info
          predicates:
            - Path=/userinfo/**,/note/**
        - id: resource
          uri: http://localhost:8082 # http://localhost:8082 # lb://user_info
          predicates:
            - Path=/static/**,/resource/**
            #- Method=GET

        - id: article
          uri: http://localhost:8083 # http://localhost:8082 # lb://user_info
          predicates:
            - Path=/article/**

  main:
    web-application-type: reactive